### ISSUE TITLE
[BUG] NPCstats

### ISSUE THREAD

**Issue by NamelessButler** [yotan-dev/mad-island-mods#2]
### Bug
> NPC Stats

Issue → Makes all (Non Captive/Tamed) Natives NPCs invisible.

### Active Mods
- NpcStats
- YotanModCore
- YoUnnoficialPatches

### Game Version
> 0.2.0

Note: Tested enabling and disabling multiple mods which I play with until arrived at this one.
The only thing I haven't tried is only having **NpcStats** and **YotanModCore** active without the **YoUnnoficialPatches**.

### Preview
![image](https://github.com/user-attachments/assets/ff525e42-95a7-437a-a306-cf1f687e8bdb)

**Comment by yotan-dev** [comment]
Hey there, sorry, I completely missed this.

Thank you for the detailed report, this was great and really helped me tracing it!

I made a new release fixing the issue. please let me know if you still have an issue.

**Comment by NamelessButler** [comment]
@yotan-dev 
Seems like the issue still persist.

```
[Error  : Unity Log] MissingFieldException: Field not found: int .StatsData.upAttack Due to: Could not find field in class
Stack trace:
NpcStats.Patches.NpcSpawnPatch.Post_NPCLevelSet (CommonStates common) (at <9dc1139c6fbd449a9d9016ca17ff0191>:0)
(wrapper dynamic-method) NPCManager.DMD<NPCManager::NPCLevelSet>(NPCManager,CommonStates,bool)
NPCManager+<GenSpawn>d__81.MoveNext () (at <684302ef71b74488903c38804367b483>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <fbf5779b092846b08cf20985bc90dcd0>:0)
```
The current error popping up in the Debugger.

**Comment by yotan-dev** [comment]
weird.. I can't reproduce it. I am in 0.2.2 now, but this shouldn't change it... It looks like your mods are still trying to look for the attack field from v0.1.8.... but using the current yotan mod core / npcstats plugins should work fine in v0.2.1 / v0.2.2...

Can you try downloading fresh copies of those 2? YotanModCore v1.2.0 (I will release it in a few minutes) and NpcStats v2.0.0

**Comment by NamelessButler** [comment]
Yeah,it seems YotanModCore was causing the issues.
I tested only using those from previous and actual build. Using previous YotanModCore cause the issue with npcstats but current version have that fixed.

Thnks for the hardwork.
